[package]
name = "libjpegturbo-sys"
version = "0.1.0"
authors = ["Zimon Dai <daizhuoxian@gmail.com>"]
edition = "2018"
keywords = ["jpeg", "image", "libjpeg", "libjpegturbo"]

[dependencies]

[build-dependencies]
# bindgen = "0.53.1"
cmake = "0.1.42"
